### ISSUE TITLE
alpinelinux swoole

### ISSUE THREAD

**Issue by moyee** [pinguo/php-msf-docker#20]
我试过好几次，无法成功安装swoole ，
不知道你们有没有尝试过？

提示的错误 

~/swoole-1.9.22 # ./configure --with-php-config=/usr/bin/php-config --enable-async-redis --enable-openssl^C
~/swoole-1.9.22 # make clean 1>/dev/null \
>     && make 1>/dev/null \
>     && make install
/root/swoole-1.9.22/src/os/linux_aio.c:23:27: fatal error: linux/aio_abi.h: No such file or directory
 #include <linux/aio_abi.h>

**Comment by viaweb3** [comment]
感觉这个issue，应该是提交到swoole那边呢，同志。
